[package]
name = "wasmer/build-scripts"
version = "0.1.1"

[dependencies]
"wasmer/python-native" = "=0.1.11"

[fs]
"/app" = "./"
"/cpython/lib/python3.13/site-packages" = "./wasix-site-packages"

[[command]]
name = "script"
module = "wasmer/python-native:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/app/run-tests.py"]
env = [
  "PYTHONEXECUTABLE=/bin/python",
  "PYTHONHOME=/cpython",
  "PYTHONPATH=/opt/venv/lib/python3.13/site-packages",
  "HOME=/app",
]
